version: '3.3'

# Services-Kreuzkirche Config by Niklas Arnitz 2022
# Persistent data is stored in the ./data directory
# Config files are stored in the ./config directory

services:
  # NGINX-Proxymanager
  nginx-proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      # Add any other Stream port you want to expose
    volumes:
      - ./data/nginx-proxymanager/data:/data
      - ./data/nginx-proxymanager/letsencrypt:/etc/letsencrypt

  # Nextcloud - Open Source Cloud Solution
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - "./config/nextcloud:/config"
      - '/mnt/data-volume/cloud:/data'
    restart: unless-stopped
    depends_on:
      - nextcloud-mariadb
    # Ports: 80, 443

  nextcloud-mariadb:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=ncpassword
    volumes:
      - ./data/nextcloud-mariadb:/config
    restart: unless-stopped

  # Wordpress - Production
  wordpress:
    image: wordpress:latest
    # Ports: 80
    volumes:
      - ./config/wordpress/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./data/wp-app:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - wordpress-db
    links:
      - wordpress-db

  wordpress-db:
    image: mysql:latest
    # Ports: 3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./data/wordpress/wp-data:/docker-entrypoint-initdb.d
      - ./data/wordpress/db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress

  # Wordpress - Staging
  wordpress-staging:
    image: wordpress:latest
    # Ports: 80
    volumes:
      - ./config/wordpress-staging/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./data/wordpress-staging/wp-app:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - wordpress-staging-db
    links:
      - wordpress-staging-db

  wordpress-staging-db:
    image: mysql:latest
    # Ports: 3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./data/wordpress-staging/wp-data:/docker-entrypoint-initdb.d/
      - ./data/wordpress-staging/db_data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress


  # Uptime Kuma
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    volumes:
      - "./data/uptime-kuma/:/app/data"
    # Ports: 3001
    depends_on:
      - nginx-proxymanager
      - nextcloud
      - nextcloud-mariadb
      - wordpress
      - wordpress-db

networks:
  default:
    external:
      name: nginxproxymanager