version: '3.3'

# Services-Kreuzkirche Config by Niklas Arnitz 2022
# Persistent data is stored in the ./data directory
# Config files are stored in the ./config directory

services:
  # NGINX-Proxymanager
  nginx-proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      # Add any other Stream port you want to expose
    volumes:
      - ./data/nginx-proxymanager/data:/data
      - ./data/nginx-proxymanager/letsencrypt:/etc/letsencrypt
    user: 1000
    group: 1000

  # Nextcloud - Open Source Cloud Solution
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - "./config/nextcloud:/config"
      - '/mnt/data-volume/cloud:/data'
    restart: unless-stopped
    depends_on:
      - nextcloud-mariadb
    # Ports: 80, 443

  nextcloud-mariadb:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=ncpassword
    volumes:
      - ./data/nextcloud-mariadb:/config
    restart: unless-stopped

  # Wordpress - Production
  wordpress:
    image: wordpress:latest
    # Ports: 80
    volumes:
      - ./config/wordpress/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./data/wp-app:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - wordpress-db
    links:
      - wordpress-db
    user: 1000
    group: 1000

  wordpress-db:
    image: mysql:latest
    # Ports: 3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./data/wordpress/wp-data:/docker-entrypoint-initdb.d
      - ./data/wordpress/db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    user: 1000
    group: 1000

  # Wordpress - Staging
  wordpress-staging:
    image: wordpress:latest
    # Ports: 80
    volumes:
      - ./config/wordpress-staging/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./data/wordpress-staging/wp-app:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - wordpress-staging-db
    links:
      - wordpress-staging-db
    user: 1000
    group: 1000

  wordpress-staging-db:
    image: mysql:latest
    # Ports: 3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./data/wordpress-staging/wp-data:/docker-entrypoint-initdb.d/
      - ./data/wordpress-staging/db_data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    user: 1000
    group: 1000

  # Zammad - Ticketing System
  zammad-backup:
    command: ["zammad-backup"]
    depends_on:
      - zammad-railsserver
      - zammad-postgresql
    entrypoint: /usr/local/bin/backup.sh
    environment:
      - BACKUP_SLEEP=86400
      - HOLD_DAYS=10
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASSWORD=zammad
    image: zammad/zammad-docker-compose:zammad-postgresql-5.0.3-14
    restart: unless-stopped
    volumes:
      - ./data/zammad/zammad-backup:/var/tmp/zammad
      - ./data/zammad/zammad-data:/opt/zammad
    user: 1000
    group: 1000

  zammad-elasticsearch:
    environment:
      - discovery.type=single-node
    image: zammad/zammad-docker-compose:zammad-elasticsearch-5.0.3-14
    restart: unless-stopped
    volumes:
      - ./data/zammad/elasticsearch-data:/usr/share/elasticsearch/data
    user: 1000
    group: 1000
      
  zammad-init:
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    environment:
      - MEMCACHE_SERVERS=zammad-memcached:11211
      - POSTGRESQL_USER=zammad
      - POSTGRESQL_PASS=zammad
      - REDIS_URL=redis://zammad-redis:6379
    image: zammad/zammad-docker-compose:zammad-5.0.3-14
    restart: on-failure
    volumes:
      - ./data/zammad/zammad-data:/opt/zammad
    user: 1000
    group: 1000

  zammad-memcached:
    command: memcached -m 256M
    image: memcached:1.6.10-alpine
    restart: unless-stopped
  user: 1000
  group: 1000

  zammad-nginx:
    command: ["zammad-nginx"]
    # Ports: 8080
    depends_on:
      - zammad-railsserver
    image: zammad/zammad-docker-compose:zammad-5.0.3-14
    restart: unless-stopped
    volumes:
      - ./data/zammad/zammad-data:/opt/zammad
    user: 1000
    group: 1000

  zammad-postgresql:
    environment:
      - POSTGRES_USER=zammad
      - POSTGRES_PASSWORD=zammad
    image: zammad/zammad-docker-compose:zammad-postgresql-5.0.3-14
    restart: unless-stopped
    volumes:
      - ./data/zammad/postgresql-data:/var/lib/postgresql/data
    user: 1000
    group: 1000

  zammad-railsserver:
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis
    environment:
      - MEMCACHE_SERVERS=zammad-memcached:11211
      - REDIS_URL=redis://zammad-redis:6379
    image: zammad/zammad-docker-compose:zammad-5.0.3-14
    restart: unless-stopped
    volumes:
      - ./data/zammad/zammad-data:/opt/zammad
    user: 1000
    group: 1000

  zammad-redis:
    image: redis:6.2.5-alpine
    restart: unless-stopped
    user: 1000
    group: 1000

  zammad-scheduler:
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
      - zammad-redis
    environment:
      - MEMCACHE_SERVERS=zammad-memcached:11211
      - REDIS_URL=redis://zammad-redis:6379
    image: zammad/zammad-docker-compose:zammad-5.0.3-14
    restart: unless-stopped
    volumes:
      - ./data/zammad/zammad-data:/opt/zammad
    user: 1000
    group: 1000

  zammad-websocket:
    command: ["zammad-websocket"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
      - zammad-redis
    environment:
      - MEMCACHE_SERVERS=zammad-memcached:11211
      - REDIS_URL=redis://zammad-redis:6379
    image: zammad/zammad-docker-compose:zammad-5.0.3-14
    restart: unless-stopped
    volumes:
      - ./data/zammad/zammad-data:/opt/zammad
    user: 1000
    group: 1000

  # Uptime Kuma
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    volumes:
      - "./data/uptime-kuma/:/app/data"
    # Ports: 3001
    depends_on:
      - nginx-proxymanager
      - nextcloud
      - nextcloud-mariadb
      - wordpress
      - wordpress-db
    user: 1000
    group: 1000

networks:
  default:
    external:
      name: nginxproxymanager