version: '3.3'

# Services-Kreuzkirche Config by Niklas Arnitz 2022
# Persistent data is stored in the ./data directory
# Config files are stored in the ./config directory

services:
  # NGINX-Proxymanager
  nginx-proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      # Add any other Stream port you want to expose
    volumes:
      - ./data/nginx-proxymanager/data:/data
      - ./data/nginx-proxymanager/letsencrypt:/etc/letsencrypt

  # Nextcloud - Open Source Cloud Solution
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - "./config/nextcloud:/config"
      - '/mnt/data-volume/cloud:/data'
    restart: unless-stopped
    depends_on:
      - nextcloud-mariadb
    # Ports: 80, 443

  nextcloud-mariadb:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=ncpassword
    volumes:
      - ./data/nextcloud-mariadb:/config
    restart: unless-stopped

  # Wordpress - Production
  wordpress-production:
    user: '1000'
    image: wordpress:latest
    # Ports: 80
    volumes:
      - ./config/wordpress-production/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./data/wordpress-production/wp-app:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: wordpress-production-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - wordpress-production-db

  wordpress-production-db:
    image: mysql:latest
    # Ports: 3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./data/wordpress-production/wp-app:/docker-entrypoint-initdb.d
      - ./data/wordpress-production/db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress

  # Wordpress - Staging
  wordpress-staging:
    user: '1000'
    image: wordpress:latest
    # Ports: 80
    volumes:
      - ./config/wordpress-staging/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./data/wordpress-staging/wp-app:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: wordpress-staging-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - wordpress-staging-db

  wordpress-staging-db:
    image: mysql:latest
    # Ports: 3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./data/wordpress-staging/wp-app:/docker-entrypoint-initdb.d/
      - ./data/wordpress-staging/db_data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress

  plausible-mail:
    image: bytemark/smtp
    restart: always

  plausible-db:
    image: postgres:12
    restart: always
    volumes:
      - ./data/plausible/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible-events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - ./data/plausible/event-data:/var/lib/clickhouse
      - ./config/plausible/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./config/plausible/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible-geoip:
    image: maxmindinc/geoipupdate
    restart: always
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
      - GEOIPUPDATE_ACCOUNT_ID=678129
      - GEOIPUPDATE_LICENSE_KEY=1AeerI01k9yDnl9N
    volumes:
      - ./data/plausible/geoip:/usr/share/GeoIP

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible-db
      - plausible-events_db
      - plausible-mail
      - plausible-geoip
    # Ports: 8000
    environment:
      - ADMIN_USER_EMAIL=it@ekg-durmersheim.de
      - ADMIN_USER_NAME=it
      - ADMIN_USER_PWD=2CEk4rnhmesnTu
      - BASE_URL=analytics.ekg-durmersheim.de
      - SECRET_KEY_BASE=GU+7heNSIXFNBWHaX6GB7I2YtfAnm/mNqi3QkFs+35/S1nHosqNA1TWhbT9mevHLECcbnBRtW5gEAwdUrkZl+A==
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    volumes:
      - ./data/plausible/geoip:/usr/share/GeoIP

networks:
  default:
    external:
      name: nginxproxymanager