version: '3.3'

services:
  onlyoffice:
    # Ports: 80
    restart: unless-stopped
    image: onlyoffice/documentserver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.office.entrypoints=http"
      - "traefik.http.routers.office.rule=Host(`office.ekg-durmersheim.de`)"
      - "traefik.http.middlewares.office-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.office.middlewares=office-https-redirect"
      - "traefik.http.routers.office-secure.entrypoints=https"
      - "traefik.http.routers.office-secure.rule=Host(`office.ekg-durmersheim.de`)"
      - "traefik.http.routers.office-secure.tls=true"
      - "traefik.http.routers.office-secure.service=office"
      - "traefik.http.services.office.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  default:
    external:
      name: proxy
